baseURL: "https://caldermoney.github.io/working-theory/"
relativeURLs: false
canonifyURLs: true
title: Working Theory
copyright: © Copyright Alpha. All rights reserved.
paginate: 5
languageCode: en
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
enableInlineShortcodes: true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors: ["error-remote-getjson"]
theme: hugo-8bits-theme

# sectionPagesMenu: main

enableRobotsTXT: true

taxonomies:
  category: categories
  tag: tags
  series: series

# Google Analytics
googleAnalytics: "UA-123-45"


# Parameters
params:
  dateFormat: 02 Jan 2006
  author: Marcelo Calderoni
  showSubheader: false

  copyright:
    sinceYear: 2026
    owner: Marcelo Calderoni

  languagesMenuEnabled: true

  breadcrumb:
    showCurrent: false

  pagination:
    loader: true





  # Social Networks
  # social:
  #   - network: twitter
  #     link: "#"
  #   - network: facebook
  #     link: "#"
  #   - network: instagram
  #     link: "#"
  #   - network: github
  #     link: "#"
  #   - network: google
  #     link: "#"
  #   - network: gmail
  #     link: "#"
  #   - network: medium
  #     link: "#"
  #   - network: linkedin
  #     link: "#"
  #   - network: twitch
  #     link: "#"
  #   - network: youtube
  #     link: "#"
  #   - network: reddit
  #     link: "#"
  #   - network: whatsapp
  #     link: "#"

  # Google Analytics
  googleAnalytics: "UA-123-45"


  # Contact Form
  contact:
    formAction: "#"
    validation:
      namePattern: ^[a-zA-Z]{3,}[a-zA-Z\s\-]*$
      emailPattern: ^[a-zA-Z0-9_\-\.]+@[a-zA-Z0-9_\-]+\.[a-zA-Z]{2,4}(\.[a-zA-Z]{2})?$

  background:
    image: "background-tokyo.png"
    parallax: true
    speed: 10

# Menu
languages:
  en:
    languageName: English
    weight: 10
    baseURL: "https://caldermoney.github.io/working-theory/en/"
    menu:
      main:
        - name: Home
          url: "/working-theory/en/"
          weight: 10
        - name: Posts
          url: "/working-theory/en/post/"
          weight: 50
        - name: Concepts
          url: "/working-theory/en/tags/"
          weight: 90
        - name: About
          url: "/working-theory/en/about/"
          weight: 100

  es:
    languageName: Español
    weight: 20
    baseURL: "https://caldermoney.github.io/working-theory/es/"
    menu:
      main:
        - name: Inicio
          url: "/working-theory/es/"
          weight: 10
        - name: Artículos
          url: "/working-theory/es/post/"
          weight: 50
        - name: Conceptos
          url: "/working-theory/es/tags/"
          weight: 90
        - name: Sobre
          url: "/working-theory/es/about/"
          weight: 100



privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
